import { useParams } from 'react-router-dom'

import Header from '../../components/Header'
import Banner from '../../components/Banner'
import Footer from '../../components/Footer'

const Product = () => {
  const { id } = useParams()

  return (
    <>
      <Header />
      <Banner />
      <div>Produto {id}</div>
      <Footer />
    </>
  )
}

export default Product

/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
/// ESSE ARQUIVO ESTÁ SENDO USADO PARA TESTE E APRENDIZADO PARA DEPOIS SER PASSADO PARA A PASTA PERFIL
